server:
    port: 5000

spring:
    application:
        name: authservice
    jpa:
        properties:
            hibernate.format_sql: true
            hibernate.hbm2ddl.auto: update
        show-sql: true
    datasource:
        platform: postgres
        driver-class-name: org.postgresql.Driver
        url: jdbc:${POSTGRES_URL}/authservice
        username: postgres
        password: ${POSTGRES_PASSWORD}
        initialization-mode: always
        continue-on-error: true