server:
  port: 8081

spring:
  application:
    name: messageservice
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: update
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.70/messageservice
    username: postgres
    password: ChatRoom_PASSWORD
    initialization-mode: always
    continue-on-error: true

security:
  oauth2:
    resource:
      userInfoUri: 192.168.1.70:5000/oauth/current