server:
  port: 8081

spring:
  application:
    name: messageservice
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: update
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:${POSTGRES_URL}/messageservice
    username: postgres
    password: ${POSTGRES_PASSWORD}
    initialization-mode: always
    continue-on-error: true

security:
  oauth2:
    resource:
      userInfoUri: ${AUTHSERVICE_URL}/oauth/current