server:
  port: 8080

spring:
  application:
    name: chatroomservice
  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp

#security:
#  oauth2:
#    resource:
#      userInfoUri: 192.168.1.70:5000/oauth/current